### ISSUE TITLE
R and C++11 issue on ML Server

### ISSUE THREAD

**Issue by reiselgp** [Microsoft/ML-Server#1]
I have a Microsoft R Enterprise 9.2 (Machine Learning Server) running on Azure Ubuntu VMs and we are facing an issue with R and C++11 when try to install R package prophet (Facebook Forecasting Library)

There is any solution to this problem?

Best regards.

**Comment by sdgilley** [comment]
This repo is meant to provide links to various ML Server samples.  Please post your question to https://social.msdn.microsoft.com/Forums/en-US/home?forum=MicrosoftR for support.

I'll also add this info to the readme.

Thanks.
